### ISSUE TITLE
Possible issue - Foundry article: How and Why We Unit Test Our Sass

### ISSUE THREAD

**Issue by saracope** [sparkbox/seesparkbox.com-issuetracker#2]
For the Foundry article: [How and Why We Unit Test Our Sass](https://seesparkbox.com/foundry/how_and_why_we_unit_test_our_sass)  
The paragraph noted below didn't read quite right to me. I think it is missing a word after the article reference. Possibly add the word 'section' or 'header' to clarify that statement.

_Currently:_
"**How to Use True**
There are a few ways you can implement True, but these setup instructions below are taken from the “Using Mocha (or other JS Test Runners)” explained on the True documentation website. These instructions assume you have npm and node-sass set up in your project."

_Possible fix:_
"**How to Use True**
There are a few ways you can implement True, but these setup instructions below are taken from the “Using Mocha (or other JS Test Runners)” **_section_** explained on the True documentation website. These instructions assume you have npm and node-sass set up in your project."

<img width="769" alt="screen shot 2018-11-01 at 12 29 34 pm" src="https://user-images.githubusercontent.com/2197515/47865139-cf435580-ddd1-11e8-88b0-305a4c05489c.png">

**Comment by emilykggray** [comment]
Good call, @saracope. I changed this to read "There are a few ways you can implement True, but the setup instructions below are taken from the True documentation website—see the “Using Mocha (or other JS Test Runners)” section. These instructions assume you have npm and node-sass set up in your project."

How does that read to you?

**Comment by saracope** [comment]
@emilykggray Nice!

**Comment by emilykggray** [comment]
Excellent. I'll close this. Thanks for commenting.
